2a0c:5bc0:89:a07:1e34:daff:fe7c:6436 10.149.14.102
/var/spool/PBS/mom_priv/jobs/8231430.pbs.SC: line 20: cd: rl-training: No such file or directory
/rds/general/user/cx220/home/FlapSnaking_PM_VecFrameStack_Gpu/rl-training/reset_env
uniform_base
Traceback (most recent call last):
  File "/rds/general/user/cx220/home/FlapSnaking_PM_VecFrameStack_Gpu/rl-training/launch_parallel_sb3.py", line 141, in <module>
    model.set_env(env)
  File "/rds/general/user/cx220/home/anaconda3/envs/RLSB3/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 560, in set_env
    assert env.num_envs == self.n_envs, (
AssertionError: The number of environments to be set is different from the number of environments in the model: (2 != 72), whereas `set_env` requires them to be the same. To load a model with a different number of environments, you must use `TQC.load(path, env)` instead
